<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
